module.exports={
    CATEGORY_COLLECTION: 'Category_Collection',
    SUB_CATEGORY_COLLECTION: 'Sub_Category_Collection',
    PRODUCT_COLLECTION : 'Product_Collection',
    ADDITIVE_COLLECTION : 'Additive_Collection',
    BINDER_COLLECTION: 'Binder_collection',
    EMPLOYEE_COLLECTION: 'Employee_Collection',
    CUSTOMER_COLLECTION: 'Customer_Collection',
    ADMIN_COLLECTION: 'Admin_Collection',
    FORMULA_COLLECTION: 'Formula_Collection',
    BULK_ORDER_COLLECTION: 'Bulk_Order_Collection',
    CUSTOMER_CATETGORY_COLLECTION: 'Customer_Category_Collection',
    EDITED_FROMULA_COLLECTION: 'Updated_Fromula_Collection',
    USERS_COLLECTION:'Users_Collection',
    DELETED_USERS_COLLECTION:'Deleted_Users_Collection',
    CARD_COLLECTION:'Card_Collection',
    SALES_MODIFIED_CARDS:'Sales_Modified_Cards',
    LIST_COLLECTION:'List_Collection',
    LABEL_COLLECTION:'Label_Collectin',
    CUSTOMER_FOLLOW_UP:'Customer_Follow_Up',
    BRANCH_COLLECTION:'Branch_Collection',
    CUSTOMER_PURCHASE_COLLECTION:'Customer_Purchase_Collection',
    LEDGER_UPLOADED_DATA:'Ledger_Uploaded_Data',
    PRODUCT_GROUP_COLLECTION:'Product_Group_Collection',
    EXCEL_FILE_UPLOAD:'Excel_File_Upload',
    MECHINE_TEST_DATA:'Mechine_Test_Data',
};