module.exports={
    CATEGORY_COLLECTION: 'Category_Collection',
    SUB_CATEGORY_COLLECTION: 'Sub_Category_Collection',
    PRODUCT_COLLECTION : 'Product_Collection',
    ADDITIVE_COLLECTION : 'Additive_Collection',
    BINDER_COLLECTION: 'Binder_collection',
    EMPLOYEE_COLLECTION: 'Employee_Collection',
    CUSTOMER_COLLECTION: 'Customer_Collection',
    ADMIN_COLLECTION: 'Admin_Collection',
    FORMULA_COLLECTION: 'Formula_Collection',
    BULK_ORDER_COLLECTION: 'Bulk_Order_Collection',
    CUSTOMER_CATETGORY_COLLECTION: 'Customer_Category_Collection',
    EDITED_FROMULA_COLLECTION: 'Updated_Fromula_Collection',
    USERS_COLLECTION:'Users_Collection',
    CARD_COLLECTION:'Card_Collection',
    SALES_MODIFIED_CARDS:'Sales_Modified_Cards',
    LIST_COLLECTION:'List_Collection',
};